[package]
name = "sending-props-100-components-down"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wal-core = "0.1"
wal-rsx = "0.1"
